name: Build Android Example

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  android-example:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      NDK_VERSION: 21.4.7075529
      API_LEVEL: 30
      BUILD_TOOLS: 30.0.3

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # ====================================================================
      # 新增步骤：根据社区方案，彻底修复 WORKSPACE 文件中的依赖问题
      # - 修复所有失效的 Google Storage 镜像链接
      # - 注释掉旧的 gflags 和 glog 定义
      # - 添加新的、正确的 gflags 和 glog 定义
      # ====================================================================
      - name: Fix Bazel WORKSPACE dependencies
        run: |
          echo "Fixing broken dependency URLs..."
          sed -i 's|https://storage.googleapis.com/mirror.tensorflow.org/|https://|g' WORKSPACE

          echo "Replacing gflags and glog repository definitions..."
          # 注释掉旧的、有问题的 gflags 和 glog 定义
          sed -i -e '/name = "com_github_gflags_gflags"/,/}
/s/^/#/' WORKSPACE
          sed -i -e '/name = "com_google_glog"/,/}
/s/^/#/' WORKSPACE
          
          # 在文件末尾追加社区提供的、正确的 gflags 和 glog 定义
          cat <<EOF >> WORKSPACE

git_repository(
    name = "gflags",
    remote = "https://github.com/gflags/gflags.git",
    tag = "v2.2.2",
)

git_repository(
    name = "com_google_glog",
    remote = "https://github.com/google/glog.git",
    commit = "v0.6.0",
)
EOF
          echo "WORKSPACE file patched successfully."

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python deps for TF configure
        run: |
          python -m pip install --upgrade pip
          python -m pip install "numpy==1.26.4" six

      - name: Set up Java 17 for Android cmdline-tools
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Android cmdline-tools
        run: |
          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
          curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdtools.zip
          unzip -q cmdtools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
          mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
          yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --licenses

      - name: Install Android SDK/NDK components
        run: |
          "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" \
            "platforms;android-${API_LEVEL}" \
            "build-tools;${BUILD_TOOLS}" \
            "platform-tools" \
            "ndk;${NDK_VERSION}"
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/${NDK_VERSION}" >> $GITHUB_ENV

      - name: Switch to Java 11 for Bazel
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Install Bazelisk
        run: |
          curl -L https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -o bazelisk
          chmod +x bazelisk
          sudo mv bazelisk /usr/local/bin/bazel
          bazel --version

      - name: Build Android App (fat APK)
        run: |
          PY_BIN="$(which python)"
          echo "Using PYTHON_BIN_PATH=$PY_BIN"
          bazel build -c opt \
            lyra/android_example:lyra_android_example \
            --fat_apk_cpu=armeabi-v7a,arm64-v8a \
            --copt=-DBENCHMARK \
            --repo_env=PYTHON_BIN_PATH="$PY_BIN"

      - name: Collect artifact
        run: |
          mkdir -p action-product
          cp bazel-bin/lyra/android_example/lyra_android_example.apk action-product/lyra_example-fat.apk
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lyra-android-example-fat
          path: action-product/
